version: "3.9"
services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.15.0
    container_name: elasticsearch
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
      - ES_JAVA_OPTS=-Xms1g -Xmx1g   # 1GB heap size
    ulimits:
      memlock:
        soft: -1
        hard: -1
    ports:
      - "9200:9200"
    deploy:
      resources:
        limits:
          memory: 2g
